"""add_user_ad_interactions

Revision ID: 5acaf0524bd9
Revises: b6f8ccbad7a1
Create Date: 2026-02-28 21:43:19.100119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5acaf0524bd9'
down_revision: Union[str, Sequence[str], None] = 'b6f8ccbad7a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
