"""add birth and gender to user

Revision ID: 614018eb3476
Revises: e10575c05893
Create Date: 2026-01-31 14:14:40.220227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614018eb3476'
down_revision: Union[str, Sequence[str], None] = 'e10575c05893'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hobby_posts', sa.Column('meetup_fee_info', sa.Text(), nullable=True))
    op.add_column('hobby_posts', sa.Column('meetup_status', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('birth_year_month', sa.String(length=7), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('is_stats_visible', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_stats_visible')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'birth_year_month')
    op.drop_column('hobby_posts', 'meetup_status')
    op.drop_column('hobby_posts', 'meetup_fee_info')
    # ### end Alembic commands ###
