"""add_parent_id_and_repost_to_hobby_posts

Revision ID: 85b3352e7c31
Revises: 60d1e0277e36
Create Date: 2026-02-04 22:45:12.996865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '85b3352e7c31'
down_revision: Union[str, Sequence[str], None] = '60d1e0277e36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
