"""add_user_tags_and_mood_category

Revision ID: 8656397c67df
Revises: b5c87c0faa3a
Create Date: 2026-04-18 21:09:21.561537

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8656397c67df'
down_revision: Union[str, Sequence[str], None] = 'b5c87c0faa3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # password_reset_tokens（既存の場合スキップ）
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    existing = inspector.get_table_names()

    if 'password_reset_tokens' not in existing:
        op.create_table('password_reset_tokens',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('token', sa.String(length=64), nullable=False),
        sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('is_used', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_password_reset_tokens_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_password_reset_tokens_token'), ['token'], unique=True)

    if 'user_tags' not in existing:
        op.create_table('user_tags',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('label', sa.String(length=30), nullable=False),
        sa.Column('color', sa.String(length=20), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id', 'label', name='uq_user_tag_label')
        )
        with op.batch_alter_table('user_tags', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_user_tags_id'), ['id'], unique=False)

    if 'meetup_message_reactions' not in existing:
        op.create_table('meetup_message_reactions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('reaction', sa.String(length=10), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
        sa.ForeignKeyConstraint(['message_id'], ['meetup_messages.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('message_id', 'user_id', 'reaction', name='uq_meetup_reaction')
        )
        with op.batch_alter_table('meetup_message_reactions', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_meetup_message_reactions_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_meetup_message_reactions_message_id'), ['message_id'], unique=False)

    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        cols = [c['name'] for c in inspector.get_columns('mood_logs')]
        if 'category' not in cols:
            batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        cols = [c['name'] for c in inspector.get_columns('users')]
        if 'is_mood_comment_visible' not in cols:
            batch_op.add_column(sa.Column('is_mood_comment_visible', sa.Boolean(), nullable=False, server_default='0'))
        batch_op.alter_column('public_code',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=8),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('public_code',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=7),
               existing_nullable=False)
        batch_op.drop_column('is_mood_comment_visible')

    with op.batch_alter_table('mood_logs', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('meetup_message_reactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_meetup_message_reactions_message_id'))
        batch_op.drop_index(batch_op.f('ix_meetup_message_reactions_id'))

    op.drop_table('meetup_message_reactions')
    with op.batch_alter_table('user_tags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_tags_id'))

    op.drop_table('user_tags')
    with op.batch_alter_table('password_reset_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_token'))
        batch_op.drop_index(batch_op.f('ix_password_reset_tokens_id'))

    op.drop_table('password_reset_tokens')
    # ### end Alembic commands ###
