"""add paid_friend_slots to user

Revision ID: b5c87c0faa3a
Revises: 5acaf0524bd9
Create Date: 2026-03-08 00:52:43.170758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c87c0faa3a'
down_revision: Union[str, Sequence[str], None] = '5acaf0524bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_friend_slots', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_premium', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_premium')
        batch_op.drop_column('paid_friend_slots')

    # ### end Alembic commands ###
