"""add_ad_color

Revision ID: b6f8ccbad7a1
Revises: e4f20dfddabc
Create Date: 2026-02-28 20:49:55.271760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6f8ccbad7a1'
down_revision: Union[str, Sequence[str], None] = 'e4f20dfddabc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby_posts', schema=None) as batch_op:
        batch_op.alter_column('ad_color',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'green'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby_posts', schema=None) as batch_op:
        batch_op.alter_column('ad_color',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'green'"))

    # ### end Alembic commands ###
