"""empty message

Revision ID: bf606850da7b
Revises: 3cc0ffd77493
Create Date: 2026-01-03 18:54:00.242567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf606850da7b'
down_revision: Union[str, Sequence[str], None] = '3cc0ffd77493'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_restricted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('report_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'report_count')
    op.drop_column('users', 'is_restricted')
    # ### end Alembic commands ###
