"""add_is_system_to_hobby_posts

Revision ID: e10575c05893
Revises: 595b8d1a572b
Create Date: 2026-01-12 16:24:39.018036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e10575c05893'
down_revision: Union[str, Sequence[str], None] = '595b8d1a572b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hobby_posts', sa.Column('is_system', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hobby_posts', 'is_system')
    # ### end Alembic commands ###
