"""Reset and add ad_color

Revision ID: e4f20dfddabc
Revises: 
Create Date: 2026-02-28 19:59:49.719616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f20dfddabc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby_posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ad_color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hobby_posts', schema=None) as batch_op:
        batch_op.drop_column('ad_color')

    # ### end Alembic commands ###
