"""add friend_note to friendship

Revision ID: ef8fc2847f66
Revises: d1acad4bb443
Create Date: 2025-12-28 17:00:26.848024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef8fc2847f66'
down_revision: Union[str, Sequence[str], None] = 'd1acad4bb443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('follows', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('follows', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('follows', sa.Column('target_id', sa.Integer(), nullable=False))
    op.add_column('follows', sa.Column('target_type', sa.String(), nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['user_id'], ['id'])
    op.drop_column('follows', 'follower_id')
    op.drop_column('follows', 'following_id')
    op.add_column('friendships', sa.Column('friend_note', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('friendships', 'friend_note')
    op.add_column('follows', sa.Column('following_id', sa.INTEGER(), nullable=False))
    op.add_column('follows', sa.Column('follower_id', sa.INTEGER(), nullable=False))
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'follows', 'users', ['following_id'], ['id'], ondelete='CASCADE')
    op.drop_column('follows', 'target_type')
    op.drop_column('follows', 'target_id')
    op.drop_column('follows', 'user_id')
    op.drop_column('follows', 'id')
    # ### end Alembic commands ###
